nguage: cpp
compiler:
  - gcc
install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install libstdc++6-4.6-dev
  - uname -a
  - sudo apt-get install build-essential

# Change this to your needs
script: ./test.sh
