addons:
  apt:
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo

before_install:
  - export MAKEFLAGS="-j3"
install: true
script:
  - gcc -v
  - g++ -v
  - sudo apt-cache search gcc
