addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo

before_install:
  - export MAKEFLAGS="-j3"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y

instale: true
script:
  - gcc -v
  - g++ -v
  - gcc-4.8 -v
  - g++-4.8 -v
  - sudo apt-cache search gcc
