nguage: cpp
compiler:
  - gcc
install:
  - sudo apt-get install libstdc++6-4.6-dev
  - uname -a
  - sudo apt-get install libc6-dev git-core gnupg flex bison gperf libsdl1.2-dev libesd0-dev libwxgtk2.8-dev squashfs-tools build-essential zip curl libncurses5-dev zlib1g-dev openjdk-6-jre openjdk-6-jdk pngcrush schedtool libxml2 libxml2-utils xsltproc g++-multilib lib32z1-dev lib32ncurses5-dev lib32readline-gplv2-dev

# Change this to your needs
script: ./test.sh
